version: '3.8'
services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    container_name: artemix-basics
    environment:
        AMQ_USER: quarkus
        AMQ_PASSWORD: quarkus
    ports:
      - 8161:8161
      - 61616:61616
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=homelessness
      - MYSQL_ROOT_PASSWORD=mama
      - MYSQL_USER=john
      - MYSQL_PASSWORD=mama
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

volumes:
  db:
    driver: local

